export const indianCities = [
  "Bangalore, Karnataka",
  "Mumbai, Maharashtra",
  "Delhi NCR",
  "Hyderabad, Telangana",
  "Chennai, Tamil Nadu",
  "Pune, Maharashtra",
  "Kolkata, West Bengal",
  "Ahmedabad, Gujarat",
  "Jaipur, Rajasthan",
  "Lucknow, Uttar Pradesh",
  "Chandigarh",
  "Indore, Madhya Pradesh",
  "Noida, Uttar Pradesh",
  "Gurugram, Haryana",
  "Kochi, Kerala",
  "Thiruvananthapuram, Kerala",
  "Coimbatore, Tamil Nadu",
  "Bhopal, Madhya Pradesh",
  "Nagpur, Maharashtra",
  "Visakhapatnam, Andhra Pradesh",
]
